apiVersion: v2
appVersion: "24.0.6"
deprecated: false
description: Dedicated App for using Docker-Compose on TrueNAS SCALE
home: https://truecharts.org/charts/stable/docker-compose
icon: https://truecharts.org/img/hotlink-ok/chart-icons/docker-compose.png
keywords:
  - docker-compose
  - docker
kubeVersion: ">=1.16.0-0"
name: docker-compose
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/docker-compose
type: application
version: 7.0.14
